-- HRIS Reborn - AGENDA LIVE
-- Jalankan setelah source branch feature/agenda-live dipull ke SERVER-HRIS.
-- Aman diulang: CREATE TABLE IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS AGENDA_DISPOSISI (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    KEGIATAN VARCHAR(250) NOT NULL,
    TANGGAL DATE NOT NULL,
    JAM TIME NOT NULL,
    LOKASI VARCHAR(250) NOT NULL,
    JENIS VARCHAR(20) NOT NULL,
    SUMBER_DOKUMEN VARCHAR(30) NOT NULL,
    DOCUMENT_NAME VARCHAR(255) NULL,
    DOCUMENT_PATH VARCHAR(500) NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'AKTIF',
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATE_BY VARCHAR(50) NULL,
    UPDATE_DATE DATETIME NULL,
    PRIMARY KEY (ID),
    KEY IDX_AGENDA_DISPOSISI_TANGGAL (TANGGAL),
    KEY IDX_AGENDA_DISPOSISI_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AGENDA_DISPOSISI_PESERTA (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    AGENDA_ID BIGINT NOT NULL,
    NIP VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'DITUGASKAN',
    CREATED_DATE DATETIME NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UQ_AGENDA_DISPOSISI_PESERTA (AGENDA_ID, NIP),
    KEY IDX_AGENDA_DISPOSISI_PESERTA_NIP (NIP),
    KEY IDX_AGENDA_DISPOSISI_PESERTA_AGENDA (AGENDA_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
