-- HRIS Reborn - AGENDA LIVE
-- Jalankan setelah source branch feature/agenda-live dipull ke SERVER-HRIS.
-- Aman diulang: CREATE TABLE IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS AGENDA_DISPOSISI (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    KEGIATAN VARCHAR(250) NOT NULL,
    TANGGAL DATE NOT NULL,
    JAM TIME NOT NULL,
    LOKASI VARCHAR(250) NOT NULL,
    JENIS VARCHAR(20) NOT NULL,
    SUMBER_DOKUMEN VARCHAR(30) NOT NULL,
    DOCUMENT_NAME VARCHAR(255) NULL,
    DOCUMENT_PATH VARCHAR(500) NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'AKTIF',
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATE_BY VARCHAR(50) NULL,
    UPDATE_DATE DATETIME NULL,
    PRIMARY KEY (ID),
    KEY IDX_AGENDA_DISPOSISI_TANGGAL (TANGGAL),
    KEY IDX_AGENDA_DISPOSISI_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AGENDA_DISPOSISI_PESERTA (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    AGENDA_ID BIGINT NOT NULL,
    NIP VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'DITUGASKAN',
    CREATED_DATE DATETIME NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UQ_AGENDA_DISPOSISI_PESERTA (AGENDA_ID, NIP),
    KEY IDX_AGENDA_DISPOSISI_PESERTA_NIP (NIP),
    KEY IDX_AGENDA_DISPOSISI_PESERTA_AGENDA (AGENDA_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
-- CENTRAL DOCUMENT STORAGE
-- File fisik berada di Synology HRIS-DATA.
-- ============================================================

CREATE TABLE IF NOT EXISTS HRIS_DOCUMENT (
    DOCUMENT_ID BIGINT NOT NULL AUTO_INCREMENT,
    DOCUMENT_TYPE VARCHAR(50) NOT NULL,
    ENTITY_TYPE VARCHAR(50) NOT NULL,
    ENTITY_ID VARCHAR(100) NOT NULL,
    ORIGINAL_FILENAME VARCHAR(255) NOT NULL,
    STORAGE_PATH VARCHAR(500) NOT NULL,
    MIME_TYPE VARCHAR(100) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    SHA256 CHAR(64) NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATE_BY VARCHAR(50) NULL,
    UPDATE_DATE DATETIME NULL,
    PRIMARY KEY (DOCUMENT_ID),
    UNIQUE KEY UQ_HRIS_DOCUMENT_ENTITY (DOCUMENT_TYPE, ENTITY_TYPE, ENTITY_ID),
    KEY IDX_HRIS_DOCUMENT_ENTITY (ENTITY_TYPE, ENTITY_ID),
    KEY IDX_HRIS_DOCUMENT_TYPE (DOCUMENT_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ============================================================
-- AGENDA RAPAT: PIMPINAN, QR ABSENSI, KEHADIRAN
-- ============================================================

CREATE TABLE IF NOT EXISTS AGENDA_RAPAT_META (
    EVENT_ID BIGINT NOT NULL,
    ORGANIZER_NIP VARCHAR(50) NOT NULL,
    QR_TOKEN VARCHAR(100) NOT NULL,
    QR_ACTIVE VARCHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATE_BY VARCHAR(50) NULL,
    UPDATE_DATE DATETIME NULL,
    PRIMARY KEY (EVENT_ID),
    UNIQUE KEY UQ_AGENDA_RAPAT_META_QR_TOKEN (QR_TOKEN),
    KEY IDX_AGENDA_RAPAT_META_ORGANIZER (ORGANIZER_NIP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AGENDA_RAPAT_KEHADIRAN (
    ATTENDANCE_ID BIGINT NOT NULL AUTO_INCREMENT,
    EVENT_ID BIGINT NOT NULL,
    NIP VARCHAR(50) NOT NULL,
    SCANNED_DATE DATETIME NOT NULL,
    METHOD VARCHAR(30) NOT NULL DEFAULT 'QR',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'HADIR',
    PRIMARY KEY (ATTENDANCE_ID),
    UNIQUE KEY UQ_AGENDA_RAPAT_KEHADIRAN (EVENT_ID, NIP),
    KEY IDX_AGENDA_RAPAT_KEHADIRAN_EVENT (EVENT_ID),
    KEY IDX_AGENDA_RAPAT_KEHADIRAN_NIP (NIP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Backfill metadata untuk rapat yang sudah ada.
INSERT INTO AGENDA_RAPAT_META (
    EVENT_ID, ORGANIZER_NIP, QR_TOKEN, QR_ACTIVE,
    CREATED_BY, CREATED_DATE
)
SELECT
    e.EVENT_ID,
    e.CREATED_BY,
    CONCAT('legacy-', e.EVENT_ID, '-', REPLACE(UUID(), '-', '')),
    'Y',
    e.CREATED_BY,
    COALESCE(e.CREATED_DATE, NOW())
FROM CALENDAR_EVENT e
WHERE e.EVENT_TYPE = 'RAPAT'
  AND NOT EXISTS (
      SELECT 1
      FROM AGENDA_RAPAT_META m
      WHERE m.EVENT_ID = e.EVENT_ID
  );
