-- QR Agenda Rapat: data tambahan peserta non-pegawai
-- Aman dijalankan ulang pada MariaDB yang mendukung ADD COLUMN IF NOT EXISTS.

ALTER TABLE AGENDA_RAPAT_KEHADIRAN
    ADD COLUMN IF NOT EXISTS INSTANSI VARCHAR(255) NULL AFTER EMAIL,
    ADD COLUMN IF NOT EXISTS NO_HANDPHONE VARCHAR(50) NULL AFTER INSTANSI;
