-- HRIS Reborn
-- Agenda Rapat Attendance V2
-- Employee + Non Employee / Guest
-- Run once after pulling feature/agenda-calendar-finalization.
-- Safe to re-run on MariaDB/MySQL versions supporting IF NOT EXISTS.

ALTER TABLE AGENDA_RAPAT_KEHADIRAN
    MODIFY NIP VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL;

ALTER TABLE AGENDA_RAPAT_KEHADIRAN
    ADD COLUMN IF NOT EXISTS ATTENDEE_TYPE VARCHAR(20) NOT NULL DEFAULT 'PEGAWAI' AFTER EVENT_ID,
    ADD COLUMN IF NOT EXISTS ATTENDANCE_KEY VARCHAR(100) NULL AFTER ATTENDEE_TYPE,
    ADD COLUMN IF NOT EXISTS NAME VARCHAR(150) NULL AFTER NIP,
    ADD COLUMN IF NOT EXISTS NAME_RAW VARCHAR(150) NULL AFTER NAME,
    ADD COLUMN IF NOT EXISTS EMAIL VARCHAR(255) NULL AFTER NAME_RAW,
    ADD COLUMN IF NOT EXISTS SIGNATURE_PATH VARCHAR(500) NULL AFTER EMAIL;

ALTER TABLE AGENDA_RAPAT_KEHADIRAN
    ADD UNIQUE KEY IF NOT EXISTS UQ_AGENDA_RAPAT_ATTENDANCE_KEY (EVENT_ID, ATTENDANCE_KEY),
    ADD KEY IF NOT EXISTS IDX_AGENDA_RAPAT_ATTENDEE_TYPE (ATTENDEE_TYPE);

UPDATE AGENDA_RAPAT_KEHADIRAN
SET ATTENDEE_TYPE = 'PEGAWAI'
WHERE ATTENDEE_TYPE IS NULL OR ATTENDEE_TYPE = '';

UPDATE AGENDA_RAPAT_KEHADIRAN a
JOIN PEGAWAI p ON p.NIP = a.NIP
SET
    a.NAME = COALESCE(a.NAME, p.NAMA),
    a.EMAIL = COALESCE(a.EMAIL, p.Mail),
    a.ATTENDANCE_KEY = COALESCE(a.ATTENDANCE_KEY, CONCAT('EMP:', p.NIP))
WHERE a.ATTENDEE_TYPE = 'PEGAWAI';

-- Verification
SELECT
    COLUMN_NAME,
    IS_NULLABLE,
    COLUMN_TYPE
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'AGENDA_RAPAT_KEHADIRAN'
  AND COLUMN_NAME IN (
      'ATTENDEE_TYPE',
      'ATTENDANCE_KEY',
      'NIP',
      'NAME',
      'NAME_RAW',
      'EMAIL',
      'SIGNATURE_PATH'
  )
ORDER BY ORDINAL_POSITION;
