-- HRIS Reborn - Buku Tamu
-- Jalankan sekali pada database HRIS sebelum deploy aplikasi.

CREATE TABLE IF NOT EXISTS BUKU_TAMU (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    JUDUL VARCHAR(150) NOT NULL,
    ID_UNIT_KERJA VARCHAR(50) NOT NULL,
    UNIT_KERJA_NAME VARCHAR(100) NOT NULL,
    QR_TOKEN VARCHAR(80) NOT NULL,
    QR_ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_BY VARCHAR(50) NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATE_BY VARCHAR(50) NULL,
    UPDATE_DATE DATETIME NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_BUKU_TAMU_QR_TOKEN (QR_TOKEN),
    KEY IX_BUKU_TAMU_UNIT (ID_UNIT_KERJA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS BUKU_TAMU_ENTRY (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    BUKU_TAMU_ID BIGINT NOT NULL,
    SCANNED_DATE DATETIME NOT NULL,
    NAMA_LENGKAP VARCHAR(150) NOT NULL,
    INSTANSI VARCHAR(150) NOT NULL,
    NO_HP VARCHAR(50) NOT NULL,
    KEPERLUAN VARCHAR(255) NOT NULL,
    KETERANGAN VARCHAR(255) NULL,
    PEGAWAI_NIP VARCHAR(30) NULL,
    PEGAWAI_NAMA VARCHAR(150) NULL,
    TANDA_TANGAN_PATH VARCHAR(500) NULL,
    CREATED_IP VARCHAR(64) NULL,
    USER_AGENT VARCHAR(500) NULL,
    PRIMARY KEY (ID),
    KEY IX_BUKU_TAMU_ENTRY_BOOK (BUKU_TAMU_ID),
    KEY IX_BUKU_TAMU_ENTRY_DATE (SCANNED_DATE),
    CONSTRAINT FK_BUKU_TAMU_ENTRY_BOOK
        FOREIGN KEY (BUKU_TAMU_ID) REFERENCES BUKU_TAMU(ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Daftarkan modul agar dapat diberikan melalui HAK_AKSES_FORM.
INSERT INTO MF_FORM
    (FormID, Formname, FormType, Nourut, Berkas, Modul, parentForm, HirarkiLvl)
SELECT
    'AGENDA_BUKU_TAMU', 'Buku Tamu', 'MENU', 30, 'BukuTamu.aspx', 'AGENDA', 'AGENDA', 2
WHERE NOT EXISTS (
    SELECT 1 FROM MF_FORM WHERE FormID = 'AGENDA_BUKU_TAMU'
);
