-- HRIS Calendar Notification Center V1
-- Safe migration for existing CALENDAR_NOTIFICATION records.
-- Run once against database HRIS after pulling this branch.

ALTER TABLE CALENDAR_NOTIFICATION
    ADD COLUMN SOURCE_TYPE varchar(30) NULL AFTER SENT_DATE,
    ADD COLUMN SOURCE_ID varchar(150) NULL AFTER SOURCE_TYPE,
    ADD COLUMN TITLE varchar(200) NULL AFTER SOURCE_ID,
    ADD COLUMN URL varchar(500) NULL AFTER TITLE,
    ADD COLUMN CREATED_DATE datetime NULL AFTER URL,
    ADD COLUMN READ_DATE datetime NULL AFTER CREATED_DATE,
    ADD COLUMN COMPLETED_DATE datetime NULL AFTER READ_DATE,
    ADD COLUMN IS_ACTIVE varchar(1) NOT NULL DEFAULT 'Y' AFTER COMPLETED_DATE;

UPDATE CALENDAR_NOTIFICATION n
LEFT JOIN CALENDAR_EVENT e ON e.EVENT_ID = n.EVENT_ID
SET
    n.SOURCE_TYPE = 'AGENDA_RAPAT',
    n.SOURCE_ID = CAST(n.EVENT_ID AS CHAR),
    n.TITLE = CASE
        WHEN n.MESSAGE LIKE 'Agenda baru: %' THEN SUBSTRING(n.MESSAGE, 14)
        ELSE n.MESSAGE
    END,
    n.CREATED_DATE = COALESCE(n.SENT_DATE, NOW()),
    n.IS_ACTIVE = CASE
        WHEN e.STATUS = 'TERJADWAL' THEN 'Y'
        ELSE 'N'
    END,
    n.COMPLETED_DATE = CASE
        WHEN e.STATUS = 'TERJADWAL' THEN NULL
        ELSE COALESCE(n.SENT_DATE, NOW())
    END
WHERE n.EVENT_ID IS NOT NULL
  AND n.SOURCE_TYPE IS NULL;

CREATE INDEX IX_CAL_NOTIF_NIP_ACTIVE_READ
    ON CALENDAR_NOTIFICATION (NIP, IS_ACTIVE, READ_STATUS);

CREATE INDEX IX_CAL_NOTIF_SOURCE
    ON CALENDAR_NOTIFICATION (SOURCE_TYPE, SOURCE_ID);

CREATE UNIQUE INDEX UX_CAL_NOTIF_SOURCE_NIP
    ON CALENDAR_NOTIFICATION (SOURCE_TYPE, SOURCE_ID, NIP);
