-- HRIS Reborn - Central Document Storage metadata
-- File fisik berada di Synology HRIS-DATA.
-- Jalankan setelah source branch feature/agenda-notulen-storage dipull.

CREATE TABLE IF NOT EXISTS HRIS_DOCUMENT (
    DOCUMENT_ID BIGINT NOT NULL AUTO_INCREMENT,
    DOCUMENT_TYPE VARCHAR(50) NOT NULL,
    ENTITY_TYPE VARCHAR(50) NOT NULL,
    ENTITY_ID VARCHAR(100) NOT NULL,
    ORIGINAL_FILENAME VARCHAR(255) NOT NULL,
    STORAGE_PATH VARCHAR(500) NOT NULL,
    MIME_TYPE VARCHAR(100) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    SHA256 CHAR(64) NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATE_BY VARCHAR(50) NULL,
    UPDATE_DATE DATETIME NULL,
    PRIMARY KEY (DOCUMENT_ID),
    UNIQUE KEY UQ_HRIS_DOCUMENT_ENTITY (DOCUMENT_TYPE, ENTITY_TYPE, ENTITY_ID),
    KEY IDX_HRIS_DOCUMENT_ENTITY (ENTITY_TYPE, ENTITY_ID),
    KEY IDX_HRIS_DOCUMENT_TYPE (DOCUMENT_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
