-- HRIS Reborn
-- Kesamaptaan module
-- Run once after pulling feature/agenda-calendar-finalization.

CREATE TABLE IF NOT EXISTS KESAMAPTAAN_KEGIATAN (
    KEGIATAN_ID BIGINT NOT NULL AUTO_INCREMENT,
    JUDUL VARCHAR(200) NOT NULL,
    HARI VARCHAR(20) NOT NULL,
    TANGGAL DATE NOT NULL,
    JAM TIME NOT NULL,
    QR_TOKEN VARCHAR(120) NOT NULL,
    QR_ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'TERJADWAL',
    PDF_PATH VARCHAR(500) NULL,
    PDF_SHA256 VARCHAR(64) NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    UPDATE_BY VARCHAR(50) NULL,
    UPDATE_DATE DATETIME NULL,
    PRIMARY KEY (KEGIATAN_ID),
    UNIQUE KEY UQ_KESAMAPTAAN_QR_TOKEN (QR_TOKEN),
    KEY IDX_KESAMAPTAAN_TANGGAL (TANGGAL),
    KEY IDX_KESAMAPTAAN_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS KESAMAPTAAN_KEHADIRAN (
    KEHADIRAN_ID BIGINT NOT NULL AUTO_INCREMENT,
    KEGIATAN_ID BIGINT NOT NULL,
    NIP VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    NAMA VARCHAR(150) NOT NULL,
    SIGNATURE_PATH VARCHAR(500) NULL,
    SCANNED_DATE DATETIME NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'HADIR',
    PRIMARY KEY (KEHADIRAN_ID),
    UNIQUE KEY UQ_KESAMAPTAAN_KEHADIRAN (KEGIATAN_ID, NIP),
    KEY IDX_KESAMAPTAAN_KEHADIRAN_KEGIATAN (KEGIATAN_ID),
    KEY IDX_KESAMAPTAAN_KEHADIRAN_NIP (NIP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS KESAMAPTAAN_DOKUMENTASI (
    DOKUMENTASI_ID BIGINT NOT NULL AUTO_INCREMENT,
    KEGIATAN_ID BIGINT NOT NULL,
    ORIGINAL_FILENAME VARCHAR(255) NOT NULL,
    STORAGE_PATH VARCHAR(500) NOT NULL,
    MIME_TYPE VARCHAR(100) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    SHA256 VARCHAR(64) NOT NULL,
    SORT_ORDER INT NOT NULL DEFAULT 1,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    PRIMARY KEY (DOKUMENTASI_ID),
    KEY IDX_KESAMAPTAAN_DOK_KEGIATAN (KEGIATAN_ID),
    KEY IDX_KESAMAPTAAN_DOK_ORDER (KEGIATAN_ID, SORT_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SELECT TABLE_NAME
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME IN (
      'KESAMAPTAAN_KEGIATAN',
      'KESAMAPTAAN_KEHADIRAN',
      'KESAMAPTAAN_DOKUMENTASI'
  )
ORDER BY TABLE_NAME;
