-- HRIS Reborn - Rekam Medis Agenda
-- Kegiatan Rekam Medis + QR + peserta/pemeriksaan.
-- Aman diulang.

CREATE TABLE IF NOT EXISTS REKAM_MEDIS_KEGIATAN (
    KEGIATAN_ID BIGINT NOT NULL AUTO_INCREMENT,
    JENIS VARCHAR(20) NOT NULL,
    JUDUL VARCHAR(250) NOT NULL,
    TANGGAL DATE NOT NULL,
    JAM TIME NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'TERJADWAL',
    QR_TOKEN VARCHAR(120) NOT NULL,
    QR_ACTIVE VARCHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50) NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (KEGIATAN_ID),
    UNIQUE KEY UQ_REKAM_MEDIS_KEGIATAN_QR (QR_TOKEN),
    KEY IX_REKAM_MEDIS_KEGIATAN_JENIS (JENIS),
    KEY IX_REKAM_MEDIS_KEGIATAN_TANGGAL (TANGGAL),
    KEY IX_REKAM_MEDIS_KEGIATAN_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS REKAM_MEDIS_PESERTA (
    PESERTA_ID BIGINT NOT NULL AUTO_INCREMENT,
    KEGIATAN_ID BIGINT NOT NULL,
    JENIS_PESERTA VARCHAR(20) NOT NULL,
    NIP VARCHAR(50) NULL,
    NIK VARCHAR(32) NULL,
    NAMA VARCHAR(150) NOT NULL,
    UNIT_KERJA VARCHAR(100) NULL,
    INSTANSI VARCHAR(200) NULL,
    EMAIL VARCHAR(150) NULL,
    NO_HANDPHONE VARCHAR(50) NULL,
    STATUS_PEMERIKSAAN VARCHAR(20) NOT NULL DEFAULT 'MENUNGGU',
    REKAM_ID BIGINT NULL,
    SCANNED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (PESERTA_ID),
    UNIQUE KEY UQ_REKAM_MEDIS_PESERTA_PEGAWAI (KEGIATAN_ID, NIP),
    UNIQUE KEY UQ_REKAM_MEDIS_PESERTA_NONPEGAWAI (KEGIATAN_ID, NIK),
    KEY IX_REKAM_MEDIS_PESERTA_KEGIATAN (KEGIATAN_ID),
    KEY IX_REKAM_MEDIS_PESERTA_STATUS (STATUS_PEMERIKSAAN),
    KEY IX_REKAM_MEDIS_PESERTA_NIP (NIP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
