CREATE TABLE IF NOT EXISTS REKAM_MEDIS_KEGIATAN (
    KEGIATAN_ID BIGINT NOT NULL AUTO_INCREMENT,
    JENIS VARCHAR(20) NOT NULL,
    JUDUL VARCHAR(250) NOT NULL,
    LOKASI VARCHAR(250) NULL,
    TANGGAL DATE NOT NULL,
    JAM TIME NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'TERJADWAL',
    QR_TOKEN VARCHAR(120) NOT NULL,
    QR_ACTIVE VARCHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50) NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (KEGIATAN_ID),
    UNIQUE KEY UQ_REKAM_MEDIS_KEGIATAN_QR (QR_TOKEN),
    KEY IX_REKAM_MEDIS_KEGIATAN_JENIS (JENIS),
    KEY IX_REKAM_MEDIS_KEGIATAN_TANGGAL (TANGGAL),
    KEY IX_REKAM_MEDIS_KEGIATAN_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE REKAM_MEDIS_KEGIATAN
    ADD COLUMN IF NOT EXISTS LOKASI VARCHAR(250) NULL AFTER JUDUL;

CREATE TABLE IF NOT EXISTS REKAM_MEDIS_KEGIATAN_PETUGAS (
    PETUGAS_ID BIGINT NOT NULL AUTO_INCREMENT,
    KEGIATAN_ID BIGINT NOT NULL,
    NIP VARCHAR(50) NULL,
    NAMA_PETUGAS VARCHAR(150) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PETUGAS_ID),
    KEY IX_REKAM_MEDIS_PETUGAS_KEGIATAN (KEGIATAN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS REKAM_MEDIS_PESERTA (
    PESERTA_ID BIGINT NOT NULL AUTO_INCREMENT,
    KEGIATAN_ID BIGINT NOT NULL,
    JENIS_PESERTA VARCHAR(20) NOT NULL,
    NIP VARCHAR(50) NULL,
    NIK VARCHAR(32) NULL,
    NAMA VARCHAR(150) NOT NULL,
    UNIT_KERJA VARCHAR(100) NULL,
    INSTANSI VARCHAR(200) NULL,
    EMAIL VARCHAR(150) NULL,
    NO_HANDPHONE VARCHAR(50) NULL,
    STATUS_PEMERIKSAAN VARCHAR(20) NOT NULL DEFAULT 'MENUNGGU',
    REKAM_ID BIGINT NULL,
    SCANNED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (PESERTA_ID),
    UNIQUE KEY UQ_REKAM_MEDIS_PESERTA_PEGAWAI (KEGIATAN_ID, NIP),
    UNIQUE KEY UQ_REKAM_MEDIS_PESERTA_NONPEGAWAI (KEGIATAN_ID, NIK),
    KEY IX_REKAM_MEDIS_PESERTA_KEGIATAN (KEGIATAN_ID),
    KEY IX_REKAM_MEDIS_PESERTA_STATUS (STATUS_PEMERIKSAAN),
    KEY IX_REKAM_MEDIS_PESERTA_NIP (NIP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO MF_FORM
    (FormID, Formname, FormType, Nourut, Berkas, PanelPage, ImgUrl, NoUrutPanel, Modul, parentForm, Model, IconFA, HirarkiLvl, TransacID)
SELECT
    'REKAM_MEDIS', 'AGENDA - Rekam Medis', 'Transaksi', 4, 'input', 'Agenda',
    NULL, 4, 'HRIS', NULL, 2, 'fa fa-heartbeat', 1, 90
WHERE NOT EXISTS (
    SELECT 1 FROM MF_FORM WHERE FormID = 'REKAM_MEDIS'
);

ALTER TABLE REKAM_MEDIS_KEGIATAN_PETUGAS
    ADD COLUMN IF NOT EXISTS NIP VARCHAR(50) NULL AFTER KEGIATAN_ID;
