-- development/schema_usecase/sql/rekam_medis.sql
CREATE TABLE IF NOT EXISTS REKAM_MEDIS (
    REKAM_ID BIGINT NOT NULL AUTO_INCREMENT,
    JENIS_PASIEN VARCHAR(20) NOT NULL,
    NIP VARCHAR(50) NULL,
    NIK VARCHAR(32) NULL,
    NAMA VARCHAR(150) NOT NULL,
    UNIT_KERJA VARCHAR(100) NULL,
    INSTANSI VARCHAR(200) NULL,
    EMAIL VARCHAR(150) NULL,
    NO_HANDPHONE VARCHAR(50) NULL,
    TEKANAN_DARAH VARCHAR(20) NULL,
    NADI INT NULL,
    FREKUENSI_NAFAS INT NULL,
    SUHU DECIMAL(4,1) NULL,
    SPO2 INT NULL,
    KELUHAN TEXT NULL,
    TINDAKAN TEXT NULL,
    HASIL_KEBUGARAN VARCHAR(20) NULL,
    PEMERIKSA VARCHAR(150) NULL,
    CREATED_BY VARCHAR(50) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (REKAM_ID),
    KEY IX_REKAM_MEDIS_NIP (NIP),
    KEY IX_REKAM_MEDIS_NIK (NIK),
    KEY IX_REKAM_MEDIS_CREATED_AT (CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO MF_FORM
    (FormID, Formname, FormType, Nourut, Berkas, PanelPage, ImgUrl, NoUrutPanel, Modul, parentForm, Model, IconFA, HirarkiLvl)
SELECT
    'REKAM_MEDIS', 'Rekam Medis', 'MENU', 0, 'Rekam Medis', '/rekam-medis',
    NULL, 0, 'AGENDA', NULL, 1, 'fa-heartbeat', 2
WHERE NOT EXISTS (
    SELECT 1 FROM MF_FORM WHERE FormID = 'REKAM_MEDIS'
);
