"""
HRIS Reborn - Calendar Notification Service

Centralized Notification Center V1.

Rules:
- Recipient is always a NIP.
- Notifications are generated by source events.
- READ is independent from COMPLETED.
- Existing notification records are preserved.
- Same NIP + source type + source ID is never duplicated.
"""

from datetime import datetime

from app import db
from app.models.calendarNotificationModel import CalendarNotification


def _now():
    return datetime.utcnow()


def ensure_notification(
    nip,
    source_type,
    source_id,
    title,
    message,
    url=None,
    event_id=None,
):
    """Create one notification if this NIP/source combination is new."""
    nip = str(nip or "").strip()
    source_type = str(source_type or "").strip().upper()
    source_id = str(source_id or "").strip()

    if not nip or not source_type or not source_id:
        return None

    existing = (
        CalendarNotification.query
        .filter(
            CalendarNotification.NIP == nip,
            CalendarNotification.SOURCE_TYPE == source_type,
            CalendarNotification.SOURCE_ID == source_id,
        )
        .first()
    )
    if existing:
        return existing

    now = _now()
    row = CalendarNotification(
        EVENT_ID=event_id,
        NIP=nip,
        MESSAGE=str(message or title or "").strip()[:255],
        READ_STATUS="N",
        SENT_DATE=None,
        SOURCE_TYPE=source_type,
        SOURCE_ID=source_id,
        TITLE=str(title or "").strip()[:200],
        URL=str(url or "").strip()[:500] or None,
        CREATED_DATE=now,
        READ_DATE=None,
        COMPLETED_DATE=None,
        IS_ACTIVE="Y",
    )
    db.session.add(row)
    return row


def create_for_recipients(
    recipients,
    source_type,
    source_id,
    title,
    message,
    url=None,
    event_id=None,
):
    """Create notifications for unique recipients without duplicates."""
    rows = []
    seen = set()
    for nip in recipients or []:
        nip = str(nip or "").strip()
        if not nip or nip in seen:
            continue
        seen.add(nip)
        row = ensure_notification(
            nip=nip,
            source_type=source_type,
            source_id=source_id,
            title=title,
            message=message,
            url=url,
            event_id=event_id,
        )
        if row:
            rows.append(row)
    return rows


def complete_source(source_type, source_id):
    """Finish active notifications for a source event."""
    source_type = str(source_type or "").strip().upper()
    source_id = str(source_id or "").strip()
    if not source_type or not source_id:
        return 0

    now = _now()
    count = (
        CalendarNotification.query
        .filter(
            CalendarNotification.SOURCE_TYPE == source_type,
            CalendarNotification.SOURCE_ID == source_id,
            CalendarNotification.IS_ACTIVE == "Y",
        )
        .update(
            {
                CalendarNotification.IS_ACTIVE: "N",
                CalendarNotification.COMPLETED_DATE: now,
            },
            synchronize_session=False,
        )
    )
    return count


def deactivate_recipient(source_type, source_id, nip):
    """Deactivate one recipient when an assignment is removed."""
    source_type = str(source_type or "").strip().upper()
    source_id = str(source_id or "").strip()
    nip = str(nip or "").strip()
    if not source_type or not source_id or not nip:
        return 0

    return (
        CalendarNotification.query
        .filter(
            CalendarNotification.SOURCE_TYPE == source_type,
            CalendarNotification.SOURCE_ID == source_id,
            CalendarNotification.NIP == nip,
            CalendarNotification.IS_ACTIVE == "Y",
        )
        .update(
            {
                CalendarNotification.IS_ACTIVE: "N",
                CalendarNotification.COMPLETED_DATE: _now(),
            },
            synchronize_session=False,
        )
    )


def expire_past_dinas_luar(nip):
    """Hide Dinas Luar notifications after the latest assignment date passes."""
    from datetime import date
    from app.models.dinasLuarModel import DinasLuar
    from app.models.pegawaiModel import Pegawai

    nip = str(nip or "").strip()
    if not nip:
        return 0

    pegawai = Pegawai.query.filter(Pegawai.NIP == nip).first()
    finger_id = str(pegawai.FINGER_ID or "").strip() if pegawai else ""
    if not finger_id:
        return 0

    today = date.today()
    rows = (
        CalendarNotification.query
        .filter(
            CalendarNotification.NIP == nip,
            CalendarNotification.SOURCE_TYPE == "DINAS_LUAR",
            CalendarNotification.IS_ACTIVE == "Y",
        )
        .all()
    )

    expired = 0
    for row in rows:
        latest = (
            DinasLuar.query
            .filter(
                DinasLuar.GUID_SPRIN == row.SOURCE_ID,
                DinasLuar.FINGER_ID == finger_id,
            )
            .order_by(DinasLuar.TGL_AKHIR_DINAS_LUAR.desc())
            .first()
        )
        if latest and latest.TGL_AKHIR_DINAS_LUAR and latest.TGL_AKHIR_DINAS_LUAR.date() < today:
            row.IS_ACTIVE = "N"
            row.COMPLETED_DATE = _now()
            expired += 1

    if expired:
        db.session.commit()

    return expired


def list_for_nip(nip, limit=30):
    nip = str(nip or "").strip()
    expire_past_dinas_luar(nip)

    return (
        CalendarNotification.query
        .filter(
            CalendarNotification.NIP == nip,
            CalendarNotification.IS_ACTIVE == "Y",
            CalendarNotification.READ_STATUS == "N",
        )
        .order_by(
            CalendarNotification.CREATED_DATE.desc(),
            CalendarNotification.ID.desc(),
        )
        .limit(limit)
        .all()
    )


def unread_count(nip):
    nip = str(nip or "").strip()
    return (
        CalendarNotification.query
        .filter(
            CalendarNotification.NIP == nip,
            CalendarNotification.IS_ACTIVE == "Y",
            CalendarNotification.READ_STATUS == "N",
        )
        .count()
    )


def mark_read(notification_id, nip):
    row = (
        CalendarNotification.query
        .filter(
            CalendarNotification.ID == notification_id,
            CalendarNotification.NIP == str(nip or "").strip(),
            CalendarNotification.IS_ACTIVE == "Y",
        )
        .first()
    )
    if not row:
        return None

    if row.READ_STATUS != "Y":
        row.READ_STATUS = "Y"
        row.READ_DATE = _now()
    return row
